package control;

import java.net.URL;
import java.util.ResourceBundle;

import dao.DAO;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;
import model.entities.Fornecedor;
import model.enums.Pagamentos;
import javafx.scene.control.CheckBox;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;

import javafx.scene.control.ChoiceBox;

import javafx.scene.control.TableColumn;

public class CompraController implements Initializable {
	@FXML
	private Label lblBemVindo;
	@FXML
	private DatePicker dtData;
	@FXML
	private ChoiceBox cboFormPaga;
	@FXML
	private CheckBox chkStatus;
	@FXML
	private ChoiceBox cboForn;
	@FXML
	private TableView tbltensCompra;
	@FXML
	private TableColumn clDesc;
	@FXML
	private TableColumn clTipo;
	@FXML
	private TableColumn clCate;
	@FXML
	private TableColumn clQtde;
	@FXML
	private TableColumn clTotal;
	@FXML
	private TextField txtTotal;

	private DAO<Fornecedor> daoForn = new DAO<>(Fornecedor.class);

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		carregarCbos();
	}
	
	private void carregarCbos() {
		cboFormPaga.getItems().setAll(Pagamentos.values());
		for(Fornecedor f: daoForn.consultar("todosFornecedores")) {
			cboForn.getItems().add(f.getDesc());
		}
	}
	

	// Event Listener on Button.onMouseClicked
	@FXML
	public void inserirTbl(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void removerTbl(MouseEvent event) {
		// TODO Autogenerated
	}
}
